packages:
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - cbor-extract
  - esbuild
  - libpq

syncInjectedDepsAfterScripts:
  - build
